### ISSUE TITLE
Cant build the Zip download

### ISSUE THREAD

**Issue by kgreed** [MYOB-Technology/AccountRight_Live_API_.Net_SDK#27]
Using VS2013 as administrator, When I download the Zip, it will not build as the snk file is missing.
I had to remove signing from the projects and correct the asterix at the end of the version numbers in order to build.

When I do build there are numerous warnings one for example is

    This async method lacks 'await' operators and will run synchronously. Consider    using the 'await' operator to await non-blocking API calls, or 'await Task.Run(...)' to do CPU-bound work on a background thread.

**Comment by sawilde** [comment]
The .snk file is created when you run the build.bat file is detailed in the [readme.md]https://github.com/MYOB-Technology/AccountRight_Live_API_.Net_SDK/blob/master/README.md] 

Thanks for the info on the warnings - they don't cause any harm and we will probably just use `#pragma`s to hide them.
