### ISSUE TITLE
Problem with EmployeePayrollDetails.gender

### ISSUE THREAD

**Issue by Barsas** [MYOB-Technology/AccountRight_Live_API_.Net_SDK#40]
I'm trying to create connector from MYOB to SQL Server to share data from each other and i encountered some problem:
 - I'm using AccountRight Plus AU 2015.4.1 program. I'm using "API Sandbox Demo 28" file.
 - I have problem with Card List -> Employee -> Payroll Details -> Gender.

In AccountRight graphical interface you can choose from 3 options:
   1. Male 
   2. Female 
   3. Indeterminate 
 or leave it blank, but in SDK i have only Male, Female and NotSet(Which is blank)

If I choose 3rd option Indeterminate and try to load it in my connector program it crashes and i get this error:
```
"Encountered an operation error (https://api.myob.com/accountright/a4dfe6e4-38ee-4773-a536-284be2fbc047/Contact/EmployeePayrollDetails/)"
Inner Exception:
Error converting value "Indeterminate" to type 'System.Nullable`1[MYOB.AccountRight.SDK.Contracts.Version2.Contact.Gender]'. Path 'Items[4].Gender', line 400, position 32.
System.ArgumentException.Message:
Requested value 'Indeterminate' was not found.
```
Is there any way i can fix this ? If someone going to enter this option in AccountRight 2015.4 my connector will skip this employee and won't update his data.
Thank you
Sincerely
Gintaras

**Comment by devjack** [comment]
_Edited formatting of original ticket description_

It looks like this is related to the [MYOB.AccountRight.SDK.Contracts.Version2.Contact.EmployeePayrollDetails](https://github.com/MYOB-Technology/AccountRight_Live_API_.Net_SDK/blob/master/MYOB.API.SDK/SDK/Contracts/Version2/Contact/EmployeePayrollDetails.cs) Contract, specifically the `Gender` enum and its JSON data transformation.

**Comment by damien-c** [comment]
This issue is also occurring for me. Would be great if "Indeterminate" was supported for gender.

**Comment by damien-c** [comment]
Any idea when the next release is scheduled?

**Comment by sawilde** [comment]
we can make a release-candidate but the next official full-release will be early 2016 (jan/feb) to coincide with 2016.1 release
