### ISSUE TITLE
Artefacts? :trollface: 

### ISSUE THREAD

**Issue by ghuntley** [MYOB-Technology/AccountRight_Live_API_.Net_SDK#55]
https://github.com/MYOB-Technology/AccountRight_Live_API_.Net_SDK/blob/master/MYOB.API.SDK/SDK.Package/Package.nuspec#L54-L65

**Comment by devjack** [comment]
Evening @ghuntley, Would you be able & willing to submit a pull request for how this is best resolved? Cheers!

**Comment by sawilde** [comment]
@devjack - I think first you need to find out what @ghuntley thinks the problem is.

**Comment by sawilde** [comment]
https://grammarist.com/spelling/artefact-artifact/

artefact is an acceptable spelling
